#!/bin/bash
gzip -f /usr/local/man/man1/chonos-task.1
mandb

systemctl enable chonos-task.service
if [ -d /run/systemd/system ]; then
    systemctl daemon-reload
    systemctl start chonos-task.service
fi