#!/bin/bash
cat /etc/rc.local | grep -v "exit 0" | grep -v "chonos-taskMaster" > /tmp/rc.local

echo "exit 0" >> /tmp/rc.local
cat /tmp/rc.local > /etc/rc.local

gzip -f /usr/local/man/man1/chonos-task.1
mandb

systemctl daemon-reload
systemctl enable chonos-task.service
systemctl start chonos-task.service