.\" Manpage for chonosDDNSManager.
.\" Contact chon@grupo.cefet-rj.br.
.TH man 8 "23 Apr 2023" "1.0" "chonos-task man page"

.SH NAME
chonos-task \- ChonOS Task Manager

.SH DESCRIPTION
A scheduler of tasks for the ChonOS.

List of options and arguments:

--help      \- shows this tutorial.

--start    \- starts the ChonOS Task Manager Service.

--stop    \- stops the ChonOS Task Manager Service.

-t [command]     \- schedules the execution of [command]

.SH REPORTING BUGS
Research Group in Cognitive Hardware On Networks: chon@grupo.cefet-rj.br

.SH COPYRIGHT
Copyright © 2023 Chon Group <http://chon.group>.  License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

.SH AUTHOR
Lazarin N. M. <chon@grupo.cefet-rj.br>.
